### ISSUE TITLE
Investigate default Severity field

### ISSUE THREAD

**Issue by grahamalama** [mozilla/jira-bugzilla-integration#1043]
JBI specifies a [default field id](https://github.com/mozilla/jira-bugzilla-integration/blob/6440e9382de0e95c261f72ec9c53c81c20ddb737/jbi/models.py#L81) for users who want to sync Severity.

Twice now ([1](https://github.com/mozilla/jira-bugzilla-integration/pull/901), [2](https://github.com/mozilla/jira-bugzilla-integration/pull/1042)), we've had to override that default field to a different one.

We should:
- investigate whether `customfield_10319` should be the new default
- somehow include in the heartbeat check that if a project specifies syncing severity, the specified field is available on the screens where it's needed
- (anything else?)

**Comment by leplatrem** [comment]
> somehow include in the heartbeat check that if a project specifies syncing severity, the specified field is available on the screens where it's needed

This requires admin permission unfortunately
