### ISSUE TITLE
Container not built nor ran with current host user id

### ISSUE THREAD

**Issue by leplatrem** [mozilla/jira-bugzilla-integration#107]
`make test` fails with:

```
Creating jira-bugzilla-integration_web_run ... done
/docker-entrypoint.sh: 15: exec: bin/test.sh: Permission denied
ERROR: 126
make: *** [test] Error 126
```

The current user id is not passed as build arg (`id -u`), and the host user id does not match the container `app` id (10001).

**Comment by leplatrem** [comment]
I have tried several thing, without success, like:

```diff
--- a/docker-compose.yaml
+++ b/docker-compose.yaml
@@ -4,6 +4,10 @@ services:
     build:
       context: .
       target: development
+      args:
+        userid: ${_UID:-10001}
+        groupid: ${_GID:-10001}
+    user: ${_UID:-10001}:${_GID:-10001}
     volumes:
       - .:/app
     ports:
```

and executing the build with ``_UID=`id -u` docker-compose build``, but the container is still built with `10001:10001`

**Comment by bsieber-mozilla** [comment]
I'm not seeing this issue locally; going to close it since there was a PR merge.

Feel free to reopen if regressed or still occurring
