### ISSUE TITLE
From Direct OS.getENV to `GunicornSettings(BaseSettings)` class 

### ISSUE THREAD

**Issue by bsieber-mozilla** [mozilla/jira-bugzilla-integration#13]
Would this be a good usecase for a `GunicornSettings(BaseSettings)` class to handle picking up env vars, providing defaults, and coercing some variables to ints?

_Originally posted by @grahamalama in https://github.com/mozilla/jira-bugzilla-integration/pull/1#discussion_r816936000_

**Comment by bsieber-mozilla** [comment]
I agree this is a good candidate for an additional Settings object...but also not sure if we should; we're following the format here: https://github.com/tiangolo/uvicorn-gunicorn-docker/blob/2daa3e3873c837d5781feb4ff6a40a89f791f81b/docker-images/gunicorn_conf.py

I believe this isn't an issue--but a QOL improvement...

**Comment by grahamalama** [comment]
> I believe this isn't an issue--but a QOL improvement...

I'd agree with this. The settings setup you've taken from the link you provided works perfectly fine. I an additional settings object would make things simpler to understand and modify, though.
