### ISSUE TITLE
Improve logging output

### ISSUE THREAD

**Issue by grahamalama** [mozilla/jira-bugzilla-integration#132]
When pairing with @leplatrem yesterday, we noticed a few things about our current logging output:
- Exceptions weren't being logged to stdout
- the root logger was seemingly overwritten by some other logger

For this issue, we should investigate our logging configuration and ensure that:
- all relevant logs are emitted
- all logs are handled by `dockerflow.logging.JsonLogFormatter`
- access logs are disabled
- there are no duplicate logs

**Comment by leplatrem** [comment]
For *all relevant logs are emitted*, I would consider:
* debug of `src.*` are emitted, and potentially filtered by the handler using `LOG_LEVEL` env var
* warnings of the whole codebase + libraries

> access logs are disabled

We could make sure we already access logs via Nginx. If that's the case we can disable access logs from gunicorn and uvicorn.
If that's not the case, we could leave the application emit access logs (either via gunicorn in prod or from `uvicorn.run()` in local dev)

**Comment by leplatrem** [comment]
Fixed by #161
