### ISSUE TITLE
Run app as a single process in production

### ISSUE THREAD

**Issue by grahamalama** [mozilla/jira-bugzilla-integration#133]
From the FastAPI [docs](https://fastapi.tiangolo.com/deployment/docker/?h=deployment#replication-number-of-processes):

> If you have a cluster of machines with Kubernetes (...) then you will probably want to handle replication at the cluster level instead of using a process manager (like Gunicorn with workers) in each container.
>...
> In those cases, you would probably want to (...) [run a] single Uvicorn process instead of running something like Gunicorn with Uvicorn workers.

I think this means we should:
- change the default container CMD to run `uvicorn`
- remove `gunicorn_conf.py`

**Comment by leplatrem** [comment]
See also https://github.com/prometheus/client_python#multiprocess-mode-eg-gunicorn=

**Comment by leplatrem** [comment]
@kkleemola If we would change the container to run a single process instead of Gunicorn, would everything be in place already on the kubernetes side?

**Comment by kkleemola** [comment]
Yes.
