### ISSUE TITLE
Creating a patch attachment in bugzilla posts an empty comment to Jira

### ISSUE THREAD

**Issue by Mossop** [mozilla/jira-bugzilla-integration#154]
Here I posted a patch to phabricator for a bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1780798#c1
JBI commented in the Jira ticket with "None": https://mozilla-hub.atlassian.net/browse/MR2-3072?focusedCommentId=573910

**Comment by Mossop** [comment]
`comment.body` here is null as no comment was posted along with the attachment. We should folder out such cases.

**Comment by Mossop** [comment]
Ah actually this is because this is a private bug and so the private comment isn't sent in the webhook.

**Comment by leplatrem** [comment]
Looking at the request, it doesn't seem like there are other fields that could help figure out an attachment was posted...

**Comment by Mossop** [comment]
I think you can ignore my first comment. There probably is a comment body it just isn't being sent in the webhook as it is private. We can do like we do for the bug object, if the comment is private request it from the bugzilla API. Looks like we have the comment ID to use. I'll work on a patch tomorrow.
