### ISSUE TITLE
google-github-actions: not allowed in github org

### ISSUE THREAD

**Issue by bsieber-mozilla** [mozilla/jira-bugzilla-integration#19]
```google-github-actions/setup-gcloud@v0 is not allowed to be used in mozilla/jira-bugzilla-integration. Actions in this workflow must be: within a repository that belongs to your Enterprise account, created by GitHub or match the following: !/mozilla/**, !mozilla/**, ./**, 10up/wpcs-action@*, aws-actions/*, docker/*, pypa/gh-action-pypi-publish@v1.4.2, slackapi/slack-github-action@*, codecov/codecov-action@v2.```

EDIT:
Link to bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1759241

**Comment by bsieber-mozilla** [comment]
hi @aerickson-admin and @cknowles-admin,

I'm curious what is the process for requesting additional actions to be allowed within the @mozilla org? 

I was hoping to add `google-github-actions` to deploy the build and pushed (to GCR) container.

**Comment by cknowles-admin** [comment]
File a bug [here](https://bugzilla.mozilla.org/enter_bug.cgi?product=mozilla.org&component=Github%3A+Administration), and we can get it routed to secops and then added.  The main concern is that actions are an org-wide change only - unless you embed the action in the repo, which is allowed, but not super flexible.

**Comment by bsieber-mozilla** [comment]
Thanks @cknowles-admin!

**Comment by bsieber-mozilla** [comment]
Hi @cknowles-admin  (no rush on responding)

If I fork the [repo where this action exists](https://github.com/google-github-actions/setup-gcloud) into the mozilla org--if I'm reading that error message correctly--it could make the action potentially usable, would that be acceptable while waiting for secops to process the bug?

**Comment by cknowles-admin** [comment]
I have trouble believing it's that easy to circumvent the "only listed actions" setting that the org has -  Sadly the "is it acceptable" question is the one that secops needs to answer.  @hwine do you have thoughts?  (Feel free to just do it all in the bug.)

**Comment by bsieber-mozilla** [comment]
Closing this issue; thanks @cknowles-admin!
