### ISSUE TITLE
How to determine Total Count vs Success Count of Metrics/Instrumented Client?

### ISSUE THREAD

**Issue by bsieber-mozilla** [mozilla/jira-bugzilla-integration#191]
https://github.com/mozilla/jira-bugzilla-integration/blob/fcb739081a5c56ad39a4d4cf2bc962a1c0ec295a/jbi/services.py#L47-L52

The '.count' element here appears to be a total count

**Comment by bsieber-mozilla** [comment]
In #173 we'd like to be able to understand and display the total count of method split based on success/failure of the call.

**Comment by leplatrem** [comment]
From what I see in https://github.com/mozilla/jira-bugzilla-integration/issues/173#issuecomment-1204331174 we are going to use logs instead of StatsD metrics.
So we should probably just add a log message around these too

**Comment by bsieber-mozilla** [comment]
Are we looking to log the jira and bugzilla api calls along with other details or just the calls?

**Comment by bsieber-mozilla** [comment]
General question: 
Do we have enough as is to collect the desired data? Are we looking to add more logs/metrics?

**Comment by bsieber-mozilla** [comment]
https://mozilla-hub.atlassian.net/browse/SVCSE-707
