### ISSUE TITLE
Create a Grafana alert if not Webhook request received for X minutes

### ISSUE THREAD

**Issue by leplatrem** [mozilla/jira-bugzilla-integration#193]
This way we would be alerted when the Bugzilla Webhook gets disabled (see #181 )

**Comment by leplatrem** [comment]
I created this alert. I'll close the issue, but we will reopen it if we don't receive alerts when webhooks is down

<img width="895" alt="Screenshot 2022-08-04 at 18 26 21" src="https://user-images.githubusercontent.com/546692/182902507-29efc8a3-1833-4ad7-96fc-c7d4483d3f64.png">

**Comment by bsieber-mozilla** [comment]
Thanks for creating this; what's the notification channel: email, slack?

(I'm guessing email?)

**Comment by grahamalama** [comment]
I saw this alert go off a few times over the weekend. I'm guessing we'll always see less activity over the weekend -- is there a way to adjust the alert to account for this?

**Comment by leplatrem** [comment]
I increased the threshold to 2H
