### ISSUE TITLE
Changes are confusing on the Jira side

### ISSUE THREAD

**Issue by clouserw** [mozilla/jira-bugzilla-integration#210]
About a week ago I had [one of my Jira tickets](﻿﻿https://mozilla-hub.atlassian.net/browse/FXA-5729) have its summary changed by "Jira Automation".  I didn't know why and asked jira-support for input and they couldn't tell me what happened.  So I changed it back.

Later I learned someone [had set a field in a bugzilla ticket](https://mozilla.slack.com/archives/C016BTJKM9B/p1660317267108649) which had triggered the modification.

I'd recommend adding a comment or some kind of link back to the bugzilla ticket so the Jira owners know what is happening.  

Thanks!

**Comment by jchaupitre** [comment]
The initial problem here is that a bugzilla user posted a JIRA URL in the See Also not knowing that this would trigger the JBI sync. 

Could the JBI sync checks that both there's a JIRA URL in the See Also AND that there's a whiteboard tag that was mapped in JBI for that JIRA project ?
