### ISSUE TITLE
Do we need so many Sentry transactions?

### ISSUE THREAD

**Issue by leplatrem** [mozilla/jira-bugzilla-integration#215]
In the week of 15 to 22nd of August, the hits on the `__lbheartbeat__`  endpoint led to 2.6 millions Sentry transactions.
<img width="303" alt="Screenshot 2022-08-23 at 11 24 26" src="https://user-images.githubusercontent.com/546692/186122719-72cd53a6-32cf-4123-b20c-6a401525b465.png">

Do we need them? Do they cost anything? Should we disable performance reports?

**Comment by grahamalama** [comment]
What did things look like before then?

We [recently upgraded Sentry](https://github.com/mozilla/jira-bugzilla-integration/pull/204), and part of that change involved adding an [environment variable to control the `traces_sample_rate`](https://github.com/mozilla/jira-bugzilla-integration/blob/8850baecafdaea419b49cf157b451d707ed72b8a/jbi/app.py#L28). Maybe we can set this to a lower number in production? That's what Sentry recommends, anyway. (related #212).

**Comment by grahamalama** [comment]
Another option is to adopt a dynamic sampling approach, as described [here](https://sentry-docs-git-patch-1.sentry.dev/platforms/python/performance/sampling/#dynamic-sampling-function) and suggested by @mostlygeek [here](https://github.com/mozilla/jira-bugzilla-integration/issues/361#issue-1529730556)
