### ISSUE TITLE
Map assignees correctly for assignees who don't use their jira/moco email as their exact bugmail

### ISSUE THREAD

**Issue by gijsk** [mozilla/jira-bugzilla-integration#251]
(x-ref #229)

I use a personal gmail address for my bugmail, as do a number of other people. Even when people do use their moco address in some cases they use an alias or a `+foo` suffix to help filter bugmail. This breaks the mapping of assignees in JIRA. It would be nice if we could come up with a way of fixing this. I believe there are various other places that have or have had mappings with this information - I guess ideally we'd pull it out of mozilla-central or bugzilla in some way/shape/form.

**Comment by bsieber-mozilla** [comment]
This is a feature we currently expect Jira Automation to resolve; our current domain experts can be found in the #jbi slack channel if you would like to understand the path forward.
