### ISSUE TITLE
Not able to fix "error": "ignore event target 'string'"

### ISSUE THREAD

**Issue by blackdustbb** [mozilla/jira-bugzilla-integration#318]
Hy, 
I modified .env and environment.py and fire the make start command and while i am trying to execute  bugzilla_webhook I am facing this issue can any one help me out

![Screenshot (187)](https://user-images.githubusercontent.com/112851139/202431296-f221b365-3113-4558-bcf0-68e4e7b354f3.png)

**Comment by leplatrem** [comment]
What are you trying to do?
