### ISSUE TITLE
It will automatic scan bugzilla bug and create a jira task or we need to put bug ID manually 

### ISSUE THREAD

**Issue by blackdustbb** [mozilla/jira-bugzilla-integration#328]
It will automatic scan bugzilla bug and create a jira task or we need to put bug ID manually ?

**Comment by bsieber-mozilla** [comment]
I'm not sure I understand this question. What is it that you are trying to accomplish?

**Comment by leplatrem** [comment]
The service is just a tiny service, that is meant to get called from Bugzilla Webhooks.

You run the service somewhere, configure your Bugzilla to call the `/bugzilla_webhook` endpoint in the Webhooks settings, and then everytime a bug is created/modified Bugzilla will send a payload. If the bug has a tag in the whiteboard field that matches one Jira project of the configuration, then the service will mirror the bug with a Jira ticket.
