### ISSUE TITLE
can you please tell where is webhook in 5.0.6, I am not able to find it in the preferences tag

### ISSUE THREAD

**Issue by blackdustbb** [mozilla/jira-bugzilla-integration#333]
can you please tell where is webhook in 5.0.6, I am not able to find it in the preferences tag

**Comment by bsieber-mozilla** [comment]
I believe this is a question for whomever is administering your Bugzilla instance, you'll need to have this feature enabled as well as permissions to use the Bugzilla webhooks.

_Closing this issue as it pertains to Bugzilla administration._
