### ISSUE TITLE
Add `rid` (request id) to logs

### ISSUE THREAD

**Issue by grahamalama** [mozilla/jira-bugzilla-integration#344]
To make it easier to quickly find all log lines related to a request, we might consider adding a "request id" in our logs. This is specified as an optional [`MozLog`](https://wiki.mozilla.org/Firefox/Services/Logging#MozLog_application_logging_standard) field:
```
rid | string | unique request id for correlating other log lines | optional
```

This would help us, for example, quickly find all of the operations that were performed for one webhook request.

**Comment by bsieber-mozilla** [comment]
I like the idea of adding this! Being able to filter the logs more easily would be helpful.

What type of string/id? UUID? Any randomly unique enough value?

**Comment by leplatrem** [comment]
We could configure Nginx to set a `X-Request-Id` header on the request, and read it from FastApi (or using starlette-context)

There is apparently something available natively:
https://nginx.org/en/docs/http/ngx_http_core_module.html#var_request_id
