### ISSUE TITLE
Prevent __lbheartbeat__ from sending Sentry Transactions

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/jira-bugzilla-integration#361]
Sentry is getting millions of transaction records for `__lbheartbeat__`.  The last report was 7.1 million/month.  The sentry docs say we need a `traces_sampler` on the `init`, https://sentry-docs-git-patch-1.sentry.dev/platforms/python/configuration/filtering/#filtering-transaction-events.

**Comment by grahamalama** [comment]
Hey @mostlygeek, this is a duplicate of #215. I'll close this issue, and we make #215 a priority.
