### ISSUE TITLE
Updating a bug removes any labels added directly in Jira

### ISSUE THREAD

**Issue by davehunt** [mozilla/jira-bugzilla-integration#393]
I noticed that any labels added in Jira before linking it to a bug were removed when the initial sync happened. Ideally, the sync would merge the existing labels with those from the whiteboard. I realise this would mean that removing whiteboard entries will leave them as labels in Jira, but this is less destructive than the current behaviour.

**Comment by bsieber-mozilla** [comment]
related: https://github.com/mozilla/jira-bugzilla-integration/issues/378

**Comment by bsieber-mozilla** [comment]
@mozilla/jbi-core; looking for some thoughts/feedback here. 

I'm thinking we move forward with option 1 presented below; that way the source of truth is determined by the flag--but initial reflection allows for usage of labels/tags from bz for triage

----

https://github.com/mozilla/jira-bugzilla-integration/issues/378#issue-1557166920


> There’s likely other options; but there a few that come to mind:
> 1. Always have whiteboard_labels constructed on creation events; only use flag on "modify" events
> 2. Separate `sync_whiteboard_labels` flag, appending  `_on_create` and `_on_update`
>     a. Issues can be constructed with whiteboard labels--but not overwritten in jira if `_on_update`  is false
> 3. Change name to `overwrite_jira_labels`
>     a. if current behavior is maintained
> 4. Change behavior to pull latest Jira labels
>     a. requires additional API call
> ```
>         jira_labels = context.jira.issue_field_value(key=issue_key, field="labels")
> ```
