### ISSUE TITLE
New integration request for DISCO please

### ISSUE THREAD

**Issue by jdragojevic** [mozilla/jira-bugzilla-integration#438]
I'd like to get a bugzilla whiteboard [DISCO-] to Jira (DISCO project) integration setup to use the jira-bugzilla integration, please.

**Comment by bsieber-mozilla** [comment]
@jdragojevic I've added the whiteboard tag and Jira project mapping to the production configuration--this is visible in PR #439.

Next steps are:
- merge PR
- release new jbi version
- use wb tag 

---

this whiteboard tag mapping is using the default action; if additional functional is required this [readme show additional options](https://github.com/mozilla/jira-bugzilla-integration#action-configuration)--you could also look at alternate actions configuration [here](https://github.com/mozilla/jira-bugzilla-integration/blob/main/config/config.prod.yaml).

**Comment by bsieber-mozilla** [comment]
@jdragojevic would it be possible to get your bugzilla user_id to associate with as the contact for this action?

_(this can be found at the end of the url in the **user_id=** query param when you click "My Profile")_
<img width="269" alt="Screenshot 2023-03-22 at 1 58 31 PM" src="https://user-images.githubusercontent.com/53873986/227036534-713c0991-5fef-4e13-900b-3a43739e0af5.png">

**Comment by jdragojevic** [comment]
user_id=624105

**Comment by bsieber-mozilla** [comment]
Thanks @jdragojevic! The default jbi integration should be released in the next hour or so. The [DISCO-] wb tag will be enabled when the v4.2.1 version of JBI is released.

**Comment by bsieber-mozilla** [comment]
This is now live in production--closing this issue; feel free to reopen if this integration does not align to expectactions!

Cheers!
