### ISSUE TITLE
Add monitoring for "Data Platform and Tools" product

### ISSUE THREAD

**Issue by scholtzan** [mozilla/jira-bugzilla-integration#478]
Follow-up for https://github.com/mozilla/jira-bugzilla-integration/pull/470#issuecomment-1507719292

The Bugzilla ["Data Platform and Tools" product](https://bugzilla.mozilla.org/describecomponents.cgi?product=Data%20Platform%20and%20Tools) is currently not being observed. Could it be added to the list?

**Comment by bsieber-mozilla** [comment]
"Data Platform and Tools" Product events are now being observed by production.

<img width="1076" alt="Screenshot 2023-04-20 at 10 59 07 AM" src="https://user-images.githubusercontent.com/53873986/233449470-ee691433-d416-48be-9329-7446315ece91.png">
