### ISSUE TITLE
Decouple Jira issue creation and updates from whiteboard tag to issue label syncing

### ISSUE THREAD

**Issue by grahamalama** [mozilla/jira-bugzilla-integration#517]
JBI currently syncs the whiteboard tags of a bug with Jira issue labels when they are created or updated. This assumes that:
- the Jira automation service account has the ability to add labels to Jira issues
- the project is configured to include labels as a field on the Create / Update issue [screens](https://support.atlassian.com/jira-cloud-administration/docs/configure-issue-screens/#Configure-a-screen--x27-s-tabs-and-fields)

Failing to account for these assumptions being false leads to issues with creating issues, as evidenced in this [Sentry alert](https://mozilla.sentry.io/issues/3571741650/?project=6364263)

To prevent potential syncing failures, we should modify the current workflow. This ticket aims to decouple the syncing of whiteboard tags and issue labels from creating or updating issues. By doing so, even if the assumptions mentioned above are not met, the creation of an issue will not be blocked.

**Comment by grahamalama** [comment]
@leplatrem thinking about this a bit more, I'm wondering if we're leading ourselves down a path where we send double the amount of requests we need. Right now, here's the flow of creating an issue when `sync_whiteboard_labels` is enabled:
<details><summary>Current Issue creation flow</summary>

```mermaid
sequenceDiagram
    Bugzilla ->> JBI: POST /bugzilla_webhook (bug.create payload)
    JBI ->> Jira: POST /issue (Create issue, which includes labels)
    Jira -->> JBI: HTTP 2xx (Issue created)
    JBI -->> Bugzilla: HTTP 2xx (Webhook processed)
```

</details> 

As we discovered, this isn't very resilient. We need to check that we're _able_ to add labels first. With the `maybe_update_labels` approach, I think that'd look like:
<details><summary>Create issue, then sync labels</summary>

```mermaid
sequenceDiagram
    Bugzilla ->> JBI: POST /bugzilla_webhook (bug.create payload)
    JBI ->> Jira: POST /issue (Create Issue)
    Jira -->> JBI: HTTP 2xx (Issue created)
    JBI ->> Jira: GET /createmeta (Check ability to add labels)
    Jira -->> JBI: HTTP 2xx (Ability to add labels confirmed)
    JBI ->> Jira: PUT /issue/<issue_id>/labels (Add whiteboard tags as labels)
    Jira -->> JBI: HTTP 2xx (Labels added)
    JBI -->> Bugzilla: HTTP 2xx (Webhook processed)
```

</details> 

And for every `maybe` step where we need to do a "preflight" check (status, resolution,  etc) we'd potentially add two additional HTTP calls to Jira:
- one for the preflight check
- one to carry out the step

What if instead, we did something like this:


<details><summary>Build issue creation dict, then create</summary>

```mermaid
sequenceDiagram
    Bugzilla ->> JBI: POST /bugzilla_webhook (bug.create payload)
    JBI -->> JBI: Build issue data from bug data
    JBI ->> Jira: GET /createmeta (Check ability to add labels)
    Jira -->> JBI: HTTP 2xx (Ability to add labels confirmed)
    JBI -->> JBI: Add whiteboard tags as labels to issue data
    JBI ->> Jira: POST /issue (Create issue with built data)
    Jira -->> JBI: HTTP 2xx (Issue created)
    JBI -->> Bugzilla: HTTP 2xx (Webhook processed)
```

</details> 

Then, every `maybe` step is effectively just the "preflight" check, where a successful check means adding the data to the data to be created or updated, and failed check means adding the result to whatever message we report back to the user as "here's what didn't sync"

**Comment by leplatrem** [comment]
I wouldn't necessarily try to limit the number of requests to the Jira API if the overall result is safe and robust.

Another approach is to catch `400 invalid request` responses in all the `maybe_*` step, instead of crashing.

```diff
diff --git a/jbi/actions/steps.py b/jbi/actions/steps.py
index 2864aa9..0ca4fe6 100644
--- a/jbi/actions/steps.py
+++ b/jbi/actions/steps.py
@@ -187,7 +187,16 @@ def maybe_update_issue_status(context: ActionContext, **parameters):
         return context, ()

     if context.operation == Operation.CREATE:
-        resp = jira.update_issue_status(context, jira_status)
+        try:
+            resp = jira.update_issue_status(context, jira_status)
+        except requests_errors.HTTPError as exc:
+            if exc.responses.status_code != 400:
+                raise
+            # Send warning to developers
+            logger.warning(exc.message)
+            # Alert owner of action
+            context.send_email(exc.message)
+
         return context, (resp,)

     if context.operation == Operation.UPDATE:
```

**Comment by grahamalama** [comment]
> I wouldn't necessarily try to limit the number of requests to the Jira API if the overall result is safe and robust.

I agree that limiting requests in and of itself isn't a worthy goal. My thinking though is that fewer requests leads to more safety and more robustness. 

In my mind, each request introduces a potential point of failure in communication between the services, so fewer requests mean fewer opportunities for errors. 

Also, from a debugging perspective, fewer requests mean fewer log lines to sift through when troubleshooting issues.
