### ISSUE TITLE
Clearly document that JBI does not sync private bugs

### ISSUE THREAD

**Issue by grahamalama** [mozilla/jira-bugzilla-integration#592]
In #578 we fully disabled the ability to sync private bugs. 

We should clearly state that JBI doesn't sync private bugs in our documentation.

**Comment by hwine** [comment]
Nuance here: the security principle is we don't want to "mix audiences" here, as defined by the [Mozilla Audience Indicator](https://mozilla-hub.atlassian.net/wiki/spaces/SECURITY/pages/27170325/Mozilla+Audience+Indicator+-+Previously+Mozilla+Data+Classification#Mozilla-Audience-Indicator-Labels).

The simplest way to achieve this is to not sync non-public bugs (the current implementation).
