### ISSUE TITLE
Assess the state of our logging

### ISSUE THREAD

**Issue by grahamalama** [mozilla/jira-bugzilla-integration#645]
We realized in #644 that we weren't logging some valuable information at the correct log level. #644 was a "quick fix", but we should go through our app and examine all the logging we're doing to answer these questions:

- are we logging messages at the correct level?
- are we logging the right amount information?

**Comment by leplatrem** [comment]
Something I noticed while investigating #747 is that our `logger.debug()` messages don't show up in Log Explorer. Maybe we should log most of them at INFO level 🤷
