### ISSUE TITLE
How to measure coverage of monitoring system components? (baseline)

### ISSUE THREAD

**Issue by bsieber-mozilla** [mozilla/jira-bugzilla-integration#714]
One of our KRs is: _Increase the coverage of monitoring across critical system components._

A question presented to me was: "how can we measure this?"

---
_Can we "measure" this? How do other services systems measure this?_

---

Maybe one approach is to look at it like this?
"We're monitoring X out of Y components in the JBI system"

Where "components" are points of system to system integration; including code, cicd, infra, ...

---

Any feedback or thoughts would be appreciated!

**Comment by grahamalama** [comment]
I might have duplicated the "spirit" of this ticket in #729 and #743.

I'm going to close this issue in favor of those, since each has specific measurements / alerts they're looking to add. We can expand the scope of what we measure / add alerts to in future issues.
