### ISSUE TITLE
JBI is only logging `ignore` and `handle` operations

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/jira-bugzilla-integration#719]
<img width="1186" alt="image" src="https://github.com/mozilla/jira-bugzilla-integration/assets/83972/45653fb3-dd43-4f09-8d7d-1e31fec99bfb">

Above is a BQ screenshot of what's in the logs.  
January/23 is the last time we had stats for the other columns.

**Comment by mostlygeek** [comment]
A bit more digging: 

<img width="450" alt="image" src="https://github.com/mozilla/jira-bugzilla-integration/assets/83972/32300432-a30c-4443-9c5c-d4fba4e8f259">

**Comment by grahamalama** [comment]
That's weird because, in the Logs Explorer:

<img width="1372" alt="image" src="https://github.com/mozilla/jira-bugzilla-integration/assets/20747904/ddb74dc5-c3c7-4c48-9b74-d8a58cd4875c">

**Comment by mostlygeek** [comment]
Hmm, maybe the problem is in the BQ ingestion of the logs.  For many of the operations there is `null` for all the field values.

**Comment by grahamalama** [comment]
> maybe the problem is in the BQ ingestion of the logs

That's what it looking like. BigQuery only appears to be ingesting logs where `type` is "request.summary", and ignoring other types.
Logs Explorer:
<img width="1121" alt="image" src="https://github.com/mozilla/jira-bugzilla-integration/assets/20747904/e0784e3a-da7b-4955-b226-77504d916822">

Bigquery:
<img width="769" alt="image" src="https://github.com/mozilla/jira-bugzilla-integration/assets/20747904/c72927de-ee1a-4f8b-a17e-757abbec5eab">

**Comment by grahamalama** [comment]
https://mozilla-hub.atlassian.net/browse/SVCSE-1546

**Comment by grahamalama** [comment]
Closing this issue. See the Jira issue linked above for context. We'll focus on capturing these metrics in #729
