### ISSUE TITLE
Bugzilla comments with Markdown are misformatted in Jira

### ISSUE THREAD

**Issue by linabutler** [mozilla/jira-bugzilla-integration#723]
Hi! I recently left [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1858542#c6) on a Bugzilla bug, with some Markdown formatting: links, lists, headings, and code blocks. It was imported into Jira [like this](https://mozilla-hub.atlassian.net/browse/DISCO-2633?focusedCommentId=785864). (Please let me know if the Jira comment is inaccessible; I can attach a screenshot!)

* The numbered and ordered lists were formatted correctly.
* The links lost their formatting, and look like raw Markdown in Jira.
* The heading (`###`) looks like it was formatted as a numbered list in Jira.
* The triple-backtick code block was also imported as raw Markdown.

**Comment by leplatrem** [comment]
Thank you Lina for reporting this!
Indeed, the text is pushed "as-is": 

https://github.com/mozilla/jira-bugzilla-integration/blob/ac064a0e8bc4a00f433cba523278ff097c09bc55/jbi/services/jira.py#L291-L294

We would have to look at Jira syntax and transform it so that it renders appropriately
