### ISSUE TITLE
Capture more actions metrics with `statsd`

### ISSUE THREAD

**Issue by grahamalama** [mozilla/jira-bugzilla-integration#729]
Capture notable action events as `statd` metrics to establish system baselines. Notable action events include:

- [x] Issue created
- [x] Issue updated
- [x] Comment synced

We'll also track individual steps those actions complete in another issue.

**Comment by mostlygeek** [comment]
See: #173, since this addresses the request from that issue.

**Comment by grahamalama** [comment]
I split tracking steps out into a separate issue, since it's different enough from "major" action steps (create, update, comment).

Since we landed the change that adds these metrics, I'll close this issue as complete.
