### ISSUE TITLE
Specify the Resolution (id or name) in the string format

### ISSUE THREAD

**Issue by leplatrem** [mozilla/jira-bugzilla-integration#750]
See https://mozilla.sentry.io/issues/4605706692/

- `maybe_update_issue_resolution()` crashes with a 400
```
data = '{"fields": {"resolution": "Duplicate"}}' 

--> error = {"resolution": "Specify the Resolution (id or name) in the string format")
```

- resolutions exist in target project, field is present in modify screen
- unless the loop between the screen, my eyes, and my brain is broken, the supplied value *WAS* a string
- this blocks the webhook queue (JBI returns 500)

Ref #735 #747

**Comment by davehunt** [comment]
@leplatrem I created an API key and experimented with this. I was getting the same error, but I was able to fix it!

Instead of using the format:

```python
{"resolution": "Duplicate"}
```

We need to use the format:

```python
{"resolution": {"name": "Duplicate"}}
```
