### ISSUE TITLE
Unhandled exception in `/bugzilla_webhooks/`

### ISSUE THREAD

**Issue by grahamalama** [mozilla/jira-bugzilla-integration#787]
https://mozilla.sentry.io/issues/4704716738/?environment=stage&project=6364263&query=is%3Aunresolved&referrer=issue-stream&stream_index=0

**Comment by leplatrem** [comment]
I think we can close this now that we have this code:

https://github.com/mozilla/jira-bugzilla-integration/blob/e7b3fca0301fb84bd35ca1b12c5a89bde08dbbbf/jbi/runner.py#L179-L183
