### ISSUE TITLE
Exception in JBI can delay webhook delivery

### ISSUE THREAD

**Issue by Mossop** [mozilla/jira-bugzilla-integration#82]
If JBI returns some kind of server error (500 code) to Bugzilla when it tries to deliver a webhook event then Bugzilla keeps retrying that event, delaying delivery of any new events that occur. It has some kind of exponential back-off on retries. After five failures it waits 15 minutes between each attempt. If the webhook fails a certain number of times (100 by default but can be changed in bugzilla's config) then the webhook is just disabled entirely and the owner emailed. In our case I don't think the user's email address is valid so I suspect we just wouldn't hear about it.

The result of this is that if something goes wrong inside JBI, maybe the Jira API is down or something then the event will be retried (this would seem to resolve #33). But if something more permanent goes wrong, say a bug in how we parse the webhook payload or something, then it will completely block syncing.

This seems troublesome. The retrying is good as long as the problem is temporary but I wonder if that is something we should handle internally (as #33 seems to be talking about) rather than completely blocking later events from being processed.

Do we have any monitoring set up that would alert us on server failures?

**Comment by leplatrem** [comment]
That's a really good point.

We have monitoring in Sentry at https://sentry.io/organizations/mozilla/projects/jira-bugzilla-integration

Shall we always return `200 OK`, even if something crashes? 

(and handle retries using something like [backoff](https://github.com/litl/backoff) for the resolution of #33?)

**Comment by Mossop** [comment]
I end up doing this locally which always returns a 200 even in exceptions but also returns the traceback which is useful for debugging with ngrok: https://gist.github.com/Mossop/11eeb009e901ed12890b9380731f5545

But yeah we would have to then do some kind of local retrying of actions, and we may get into a problem where bugzilla submits a second comment action while we haven't retried the first yet and so end up with out-of-order pushes to Jira.

We'd probably need to make the bugzilla_webhook simply push into a global queue and then have some separate thing pulling from the top of the queue, attempt to submit changes and in error put back on the top of the queue and retry after a bit. But then of course whenever you update prod you risk blowing away a queue of stuff waiting to be processed...

**Comment by bsieber-mozilla** [comment]
I'm going to close this issue and continue conversations and effort to address this in #181 

If that issue misses the intent/spirit of this one; please comment/reopen!
