### ISSUE TITLE
Actions validation assumes an action has a `whiteboard_tag` parameter

### ISSUE THREAD

**Issue by grahamalama** [mozilla/jira-bugzilla-integration#89]
In our `Action` model, we specify 

```python
class Action(YamlModel):
   # ...
   parameters: dict = {}
   # ...
```

Yet in the `Actions` model, we have this validation logic:
```python
for name, action in actions.items():
    if name.lower() != action.parameters["whiteboard_tag"]:
        raise ValueError("action name must match whiteboard tag")
```

This makes the implicit assumption that every `Action` have a `whiteboard_tag`.

We should either change our config schema so a `whiteboard_tag` is a required parameter, or modify this logic somehow.

**Comment by bsieber-mozilla** [comment]
Currently all actions require a whiteboard_tag; since the only "actions" we have are all based on the whiteboard tag--in the past we had two types of action-triggers/routes: whiteboard-tag and component-based routing. 

In JBI v1 we learned that the component-based routing was less effective (and required more setup, as well as led to more stakeholder questions) than the whiteboard tagging route.

Since Actions are now officially whiteboard-tag based (in particular with the default action) I agree there's something that could be done here.

**Comment by leplatrem** [comment]
One thing that is confusing in the current design, is that the `whiteboard_tag` parameter is never read from the action code.

We could move it to become an action attribute `whiteboard_tag` instead. And this way, leave the parameters confined to the action code.

Also, we have a concept of *action name* in the code base, this could be unified with whiteboard_tag to be clearer

**Comment by bsieber-mozilla** [comment]
Plan:
- Convert to yaml list
- add whiteboard_tag field up a level as: "tag", "lookup_tag", "label", "whiteboard_tag" (remove from

**Comment by grahamalama** [comment]
Follow-on questions:
- should we limit the list of `Actions` so that the `whiteboard_tag` must be unique among all actions?
- if not, should we iterate over all the actions with a matching whiteboard tag property and execute them?
- did we say we were also going to move the `jira_project` parameter to an Action field?

**Comment by leplatrem** [comment]
> should we limit the list of Actions so that the whiteboard_tag must be unique among all actions?
>

Yes.

> if not, should we iterate over all the actions with a matching whiteboard tag property and execute them?
>

I doubt that it makes sense to duplicate contact and description between several actions with the same tag

> did we say we were also going to move the jira_project_key parameter to an Action field?
>

No, because `jira_project_key` is used in the action code, therefore it makes sense for it to be a parameter.

**Comment by grahamalama** [comment]
> jira_project_key is used in the action code, therefore it makes sense for it to be a parameter

True, but will _every_ action require the `jira_project_key` parameter? If so, maybe we should make that a required field and pass `action_instance.jira_project_key` plus `**action_instance.parameters` in to `action_module.init`. Either that, or change the typing of `parameters: dict = {}` so that we expect to have a `jira_project_key` key set, at minimum.

**Comment by grahamalama** [comment]
If none of those things are true though, then leaving things as they are makes sense.

**Comment by leplatrem** [comment]
> True, but will every action require the jira_project_key parameter?

This is not an absolute requirement, because it's not necessary to instantiate a Jira client. But this is likely to be used, since any interaction will be with a single project.

> Either that, or change the typing of parameters: dict = {} so that we expect to have a jira_project_key key set, at minimum.

If the parameter is explicitly mentioned in `init()`, don't we get the same result?
