### ISSUE TITLE
Update docs around steps available

### ISSUE THREAD

**Issue by alexcottner** [mozilla/jira-bugzilla-integration#936]
It seems like our code has gotten out of sync with our documentation around what steps are available for JBI to take. I would like us to do a short audit and updating of the docs.

Example: actions.md shows `update_issue` as being a potential step. But this does not exist and has broken into other smaller steps.

**Comment by leplatrem** [comment]
See also https://github.com/mozilla/jira-bugzilla-integration/issues/394
